env:
  - GO111MODULE=on
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go get -u github.com/gobuffalo/packr/v2/packr2
    - packr2
builds:
  - 
    id: hacker_bomb
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: hacker_bomb
    builds:
      - hacker_bomb
    replacements:
      darwin: MacOS
      linux: Linux
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    # Name templates of the built binaries that should be used.
    ids:
      - hacker_bomb
    image_templates:
      - "ghcr.io/ice2heart/hacker_bomb:latest"
      - "ghcr.io/ice2heart/hacker_bomb:{{ .Tag }}"
      - "ghcr.io/ice2heart/hacker_bomb:v{{ .Major }}"
    skip_push: auto
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - entrypoint.sh

